services:
  web-app:
    image: metalhead224/React-App:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=${HOST}
      - USERNAME=${USERNAME}
      - KEY=${KEY}
      - PORT=${PORT}
      - VIRTUAL_HOST=ecosennov.com
      - LETSENCRYPT_HOST=ecosennov.com
      - LETSENCRYPT_EMAIL=suman.osti401@gmail.com
    ports:
      - "3000:80"
    networks:
      - proxy-network

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    environment:
      - ENABLE_HTTP_REDIRECTION=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - proxy-network

  acme-companion:
    image: nginxproxy/acme-companion:latest
    container_name: nginx-proxy-acme
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=suman.osti401@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - nginx-proxy
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge

volumes:
  certs:
  vhost:
  html:
  acme: